# Generated by Django 3.1 on 2021-10-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
