# Generated by Django 3.1 on 2021-10-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211005_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.TextField(blank=True, max_length=25),
        ),
    ]
