# Generated by Django 3.1 on 2021-10-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
    ]
