# Generated by Django 3.1 on 2021-11-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
