# Generated by Django 3.1 on 2021-11-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
