# Generated by Django 3.2.9 on 2021-11-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_users_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_wishlist',
        ),
    ]
