# Generated by Django 3.1 on 2021-11-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
