# Generated by Django 3.1 on 2021-11-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
