# Generated by Django 3.1 on 2021-11-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20211124_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='day',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
